version: '3.8'

services:
  frontend:
    build: ./bookaway-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./bookaway-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/meinedb
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
